---
- name: Create chronos directory
  file:
    path: /etc/chronos
    state: directory

- name: Create chronos container env file
  template:
    src: chronos-env.j2
    dest: /etc/chronos/.chronosenv

- name: Install pip if needed
  apt:
    pkg: python-pip
    state: present
    update_cache: yes

- name: Install docker container dependencies
  pip:
    executable: /usr/bin/pip
    name: docker-py
