---
- name: Create chronos directory
  file:
    path: /etc/chronos
    state: directory

- name: Create chronos container env file
  template:
    src: chronos-env.j2
    dest: /etc/chronos/.chronosenv

