    - name: Add keyserver
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E56151BF
      when: ansible_os_family == "Debian"

    - name: Create lst file ubuntu 14
      copy: content="deb http://repos.mesosphere.com/ubuntu trusty main" dest=/etc/apt/sources.list.d/mesosphere.list
      when: ansible_os_family == "Debian" and ansible_distribution_major_version == "14"

    - name: Create lst file ubuntu 16
      copy: content="deb http://repos.mesosphere.com/ubuntu xenial main" dest=/etc/apt/sources.list.d/mesosphere.list
      when: ansible_os_family == "Debian" and ansible_distribution_major_version == "16"

    - name: Install marathon repo
      yum: pkg=http://repos.mesosphere.com/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm state=present
      when: ansible_os_family == "RedHat"

    - name: Install chronos package in Debian systems
      apt: pkg=chronos state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Install chronos package in RedHat systems
      yum: name=chronos state=present update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: start chronos
      service: name=chronos state=started enabled=yes
